[versions]
activity-compose = "1.8.0"
compose-bom = "2023.10.01"
navigation-compose = "2.7.5"
lifecycle-viewmodel-compose = "2.6.2"
lifecycle-runtime-compose = "2.6.2"
hilt-navigation-compose = "1.1.0"
core-ktx = "1.12.0"
lifecycle-runtime-ktx = "2.6.2"
datastore-preferences = "1.0.0"
work-runtime-ktx = "2.9.0"
room-runtime = "2.6.0"
kotlinx-coroutines-android = "1.7.3"
retrofit = "2.9.0"
okhttp = "4.12.0"
hilt-android = "2.48.1"
gson = "2.10.1"
timber = "5.0.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
